name: STR8 PAPER INC.
favicon: null
layout_spectrum: 0.199324
typography_spectrum: 0.330236
title: BLUPRINT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#DFC2A0'
    - '#1B1515'
    - '#9B7850'
    - '#4B3527'
  brandStrength: 0.782556
  lightness: 0.665331
  saturation: 0.774636
  rhythmicContrast: 0.957212
purpose: []
