analytics: {}
color:
  brandColors:
    - '#FEFEFE'
    - '#DFC2A0'
    - '#1B1515'
    - '#9B7850'
    - '#4B3527'
  brandStrength: 0.782556
  lightness: 0.665331
  rhythmicContrast: 0.957212
  saturation: 0.774636
cta: {}
layout_spectrum: 0.199324
name: STR8 PAPER INC.
opengraph: {}
purpose: []
typography_spectrum: 0.330236
